"""Ampliar longitud de password_hash

Revision ID: 35f43af52273
Revises: 
Create Date: 2025-08-11 13:11:07.635778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f43af52273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignaciones_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_interesado', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono_interesado', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('publicador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    op.drop_table('asignaciones_visita')
    # ### end Alembic commands ###
